FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    TERM=xterm-256color \
    COLORTERM=truecolor

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y zsh sudo wget curl git
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY target/debug/clenv /usr/local/bin/clenv

RUN chmod +x /usr/local/bin/clenv

RUN useradd -m -s /bin/zsh clenv && echo "clenv ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER clenv
WORKDIR /home/clenv

CMD ["/bin/zsh"]

