name = "zsh-autosuggestions"
description = "Fish-like autosuggestions for Zsh"
category = "zsh-plugins"

[detect]
commands = ['[ -f "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" ]']

[install.linux]
command = "git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions"

[install.macos]
command = "git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions"

[zshrc]
snippet = 'source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh'
startup_ms_estimate = 10
order = 30
